"""Board-level runtime configuration constants."""

# Panel geometry
DISPLAY_WIDTH = 360
DISPLAY_HEIGHT = 360
DISPLAY_ROTATION = 0

# Display timing
DISPLAY_QSPI_FREQ_HZ = 80_000_000
DISPLAY_RESET_LOW_MS = 100
DISPLAY_RESET_HIGH_MS = 100
DISPLAY_POST_INIT_MS = 20

# Backlight
BACKLIGHT_PWM_FREQ_HZ = 10_000
BACKLIGHT_PWM_WRAP = 1000
BACKLIGHT_DEFAULT_PERCENT = 60

# Touch
TOUCH_I2C_FREQ_HZ = 100_000
TOUCH_RESET_LOW_MS = 10
TOUCH_RESET_BOOT_MS = 100
TOUCH_CHIP_ID_REG = 0xA7
TOUCH_EXPECTED_CHIP_ID = 0x03
TOUCH_DATA_START_REG = 0x02
TOUCH_SLEEP_REG = 0xFE
TOUCH_SLEEP_OFF = 0xFF

# Scheduler / app loop
MAIN_LOOP_INTERVAL_MS = 20
TOUCH_SAMPLE_INTERVAL_MS = 20
UI_HEARTBEAT_INTERVAL_MS = 300
